signup:
  first_name: john			
  last_name: barnes
  address1: 238, 38th Street
  address2: 8th Floor
  city: New York City
  state: New York
  zip: 10018
  email_facebook: tripthishetty20@gmail.com
  pass_facebook: general1234
  email_twitter: tripthi.shetty@socialmedialink.com
  pass_twitter: general1234
  email_instagram: tripthi.shetty
  pass_instagram: general1234
  base_url_facebook: https://facebook.com
  base_url_twitter: https://twitter.com
admin:
  base_url: https://admin-staging.socialmedialink.com
  email: tripthi.testmember8@socialmedialink.com
  pass: 12345678
member:
  base_url: https://tripsprint39-staging.socialmedialink.com
  email: john.barnes@yopmail.com
  pass: 12345678
  
  